import type { KpiAnchor, KpiAnchorKey } from './transformAst'
import type { RoleEntry } from './roleEntry'

interface EmitArgs {
  roleMap: Readonly<Record<string, Readonly<RoleEntry>>>
  kpiAnchors: Partial<Record<KpiAnchorKey, KpiAnchor>>
  viewBox: { width: number; height: number }
}

// 'card-nox' → 'cardNox'
function camelize(role: string): string {
  return role.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

export function emitRolesTs({ roleMap, kpiAnchors, viewBox }: EmitArgs): string {
  const lines: string[] = []
  lines.push('// AUTO-GENERATED. DO NOT EDIT.')
  lines.push(`// Generated by scripts/buildHmiSvg.ts at ${new Date().toISOString()}`)
  lines.push('/* eslint-disable */')
  lines.push('')

  // ROLES — kpi-value-remove 제외
  lines.push('export const ROLES = {')
  for (const [role, entry] of Object.entries(roleMap)) {
    if (entry.kind === 'kpi-value-remove') continue
    lines.push(`  ${camelize(role)}: '${role}',`)
  }
  lines.push('} as const')
  lines.push('')
  lines.push('export type Role = (typeof ROLES)[keyof typeof ROLES]')
  lines.push('')

  // KPI_ANCHORS — dash 포함 키는 따옴표로 감싸서 유효 식별자로
  lines.push('export const KPI_ANCHORS = {')
  for (const [key, anchor] of Object.entries(kpiAnchors)) {
    if (!anchor) continue
    const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`
    lines.push(`  ${safeKey}: { x: ${anchor.x}, y: ${anchor.y}, textAnchor: '${anchor.textAnchor}' as const },`)
  }
  lines.push('} as const')
  lines.push('')

  // VIEW_BOX
  lines.push(`export const VIEW_BOX = { width: ${viewBox.width}, height: ${viewBox.height} } as const`)
  lines.push('')

  return lines.join('\n')
}
