// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/buildHmiSvg.ts at 2026-05-09T16:42:29.178Z
/* eslint-disable */

export const ROLES = {
  cardNox: 'card-nox',
  cardTtxm: 'card-ttxm',
  cardDwatt: 'card-dwatt',
  cardLambda: 'card-lambda',
  cardBoxNox: 'card-box-nox',
  cardBoxTtxm: 'card-box-ttxm',
  cardBoxDwatt: 'card-box-dwatt',
  cardBoxLambda: 'card-box-lambda',
  flowFuel: 'flow-fuel',
  flowNox: 'flow-nox',
  flowAir: 'flow-air',
  flowCards: 'flow-cards',
  cascade1: 'cascade-1',
  cascade2: 'cascade-2',
  cascade3: 'cascade-3',
  combustor: 'combustor',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const KPI_ANCHORS = {
  nox: { x: 1125.58, y: 142.335, textAnchor: 'start' as const },
  dwatt: { x: 1125.58, y: 315.637, textAnchor: 'start' as const },
  ttxm: { x: 1125.61, y: 228.976, textAnchor: 'start' as const },
  lambda: { x: 1125.28, y: 402.279, textAnchor: 'start' as const },
} as const

export const VIEW_BOX = { width: 1316, height: 540 } as const
