// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/buildHmiSvg.ts at 2026-05-11T00:59:58.221Z

export const ROLES = {
  cardNox: 'card-nox',
  cardTtxm: 'card-ttxm',
  cardDwatt: 'card-dwatt',
  cardLambda: 'card-lambda',
  cardBoxNox: 'card-box-nox',
  cardBoxTtxm: 'card-box-ttxm',
  cardBoxDwatt: 'card-box-dwatt',
  cardBoxLambda: 'card-box-lambda',
  flowFuel: 'flow-fuel',
  flowNox: 'flow-nox',
  flowAir: 'flow-air',
  flowCards: 'flow-cards',
  cascade1: 'cascade-1',
  cascade2: 'cascade-2',
  cascade3: 'cascade-3',
  combustor: 'combustor',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const KPI_ANCHORS = {
  syngas: { x: 51.1605, y: 195.468, textAnchor: 'start' as const },
  nqkr3: { x: 55.5057, y: 305.827, textAnchor: 'start' as const },
  'legend-fuel': { x: 25.52, y: 142.78, textAnchor: 'start' as const },
  'legend-n2': { x: 25.62, y: 253.385, textAnchor: 'start' as const },
  'legend-air': { x: 46.51, y: 405.896, textAnchor: 'start' as const },
  fsagr: { x: 239.773, y: 155.167, textAnchor: 'start' as const },
  fsag11: { x: 493.932, y: 119.694, textAnchor: 'start' as const },
  fsag11a: { x: 609.932, y: 119.694, textAnchor: 'start' as const },
  fsag12: { x: 726.773, y: 119.702, textAnchor: 'start' as const },
  nicvs1: { x: 249.773, y: 264.113, textAnchor: 'start' as const },
  nqj: { x: 455.977, y: 264.113, textAnchor: 'start' as const },
  csbhx: { x: 257.773, y: 372.113, textAnchor: 'start' as const },
  csgv: { x: 437.773, y: 372.113, textAnchor: 'start' as const },
  nox: { x: 1125.58, y: 142.335, textAnchor: 'start' as const },
  dwatt: { x: 1125.58, y: 315.637, textAnchor: 'start' as const },
  ttxm: { x: 1125.61, y: 228.976, textAnchor: 'start' as const },
  lambda: { x: 1125.28, y: 402.279, textAnchor: 'start' as const },
} as const

export const VIEW_BOX = { width: 1316, height: 540 } as const
